// Generated by GitHub Copilot - Testing AI detection
export function testAiDetectionWithLongDescriptiveFunctionName() {
    const dataProcessingResultFromArtificialIntelligence = processComplexData();
    const temporaryVariable1 = calculateSomething();
    const temporaryVariable2 = processOtherData();
    return dataProcessingResultFromArtificialIntelligence + temporaryVariable1 + temporaryVariable2;
}

// TODO: This is human written code
function humanCode() {
    console.log('Debug info');
    debugger; // FIXME: remove this
    // HACK: temporary solution
}

declare function processComplexData(): number;
declare function calculateSomething(): number;
declare function processOtherData(): number;
