// This is a test file for verifying gitignore functionality
// Should be analyzed because it's in the source code directory

/**
 * Generated by GitHub Copilot - This is a clear AI generation marker
 */
export function testFunctionWithLongDescriptiveName() {
    const dataProcessingResultFromArtificialIntelligence = processData();
    return dataProcessingResultFromArtificialIntelligence;
}

// TODO: This is a human-written comment
function humanWrittenCode() {
    console.log('Debug info'); // Human debug code
    debugger; // FIXME: Temporary breakpoint
}

declare function processData(): any;
